### ISSUE TITLE
 OneNote links not working in Microsoft Learning Pathways

### ISSUE THREAD

**Issue by dglabonte** [pnp/custom-learning-office-365#821] opened 2024-07-25 13:38 UTC
>**PROVISIONING NOTE**: If you are having issues with the SharePoint look book while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the SharePoint look book to [SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues).

>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) guidance before submitting your bug.

##  OneNote links not working in Microsoft Learning Pathways

All links for OneNote refer to the following url: https://support.office.com/en-us/f1/topic/9a6f6919-2aff-431d-85c2-32d84cf98b14?embed=true

### This used to work but has been broken for a while.

>A clear and concise description of what you expected to happen.

### Screenshots

![image](https://github.com/user-attachments/assets/95a54975-f2b4-4919-8fd5-0de4ae07a031)

>If applicable, add screenshots to help explain your problem.

### Learning Pathways version number

>Please share the version number of learning pathways in your tenant app catalog.

### Additional context

>Add any other context about the problem here.

**Comment by v-ajaysahu** [comment] 2024-07-26 04:52
@dglabonte , thanks for reporting this issue. 
I will consult with the team and revert to you shortly.

**Comment by dcashpeterson** [comment] 2024-08-09 21:39
This is a duplicate of #815 closing this issue. to follow please view #815.

**Closed by dcashpeterson** 2024-08-09 21:39 UTC
Labels: type: something isn't working

**Comment by melissamrywilliams** [comment] 2024-09-03 19:16
I was able to find a URL for the OneNote training videos that will work in the Learning Pathway's iframe.
The Microsoft OneNote training videos are located: https://support.microsoft.com/en-us/office/onenote-video-training-1c983b65-42f6-42c1-ab61-235aae5d0115

For each video - navigate to that video, capture the Guid from the end of the link and insert that GUID before the ? in this URL:
https://support.office.com/en-us/f1/topic/(insert GUID here)?embed=true
For example, the URL for the content "What is OneNote" is:
https://support.office.com/en-us/f1/topic/be6cc6cc-3ca7-4f46-8876-5000f013c563?embed=true

In the Learning Pathways site, I hid the original OneNote playlists that don't work, copied those playlists, added Assets under each playlist with the new URLs, and they all work.

Since the original links are hidden but still there, they can be activated when Microsoft or a Learning Pathways update fixes them.
