### ISSUE TITLE
[BUG] OneDrive > Manage your files with OneDrive > Restore your OneDrive: The video thumbnail doesn't load

### ISSUE THREAD

**Issue by JudiP53** [pnp/custom-learning-office-365#208] opened 2020-02-17 16:37 UTC
**Describe the bug**
Users report the video doesn't load, but there is a link that works to load the video. Unlike all the other videos in Learning Pathways, instead of a thumbnail, we see a black square with the message: "Please wait while the media loads" and a link below that graphic that launches the video

**To Reproduce**
1. Go to OneDrive > Manage your files with OneDrive > Restore your OneDrive
2. Click on video thumbnail
3. See error

**Expected behavior**
We expect to see a video thumbnail in this position on the page that, when clicked, launches the video

**Screenshots**
![image](https://user-images.githubusercontent.com/58827525/74671622-97545300-5179-11ea-949f-0eb066dc0fa5.png)

**Learning Pathways version number:**
3.0.2

**Additional context**

**Comment by juliemturner** [comment] 2020-02-17 16:46
This is actually not a bug with learning pathways but with the content on support.office.com.  If you check out the link directly you have the same issue. 

https://support.office.com/en-us/client/3bd43b2b-be98-48a8-a866-878e91263d01

Regardless, I'll let them know I just cannot control if/when it's fixed.

**Comment by juliemturner** [comment] 2020-04-06 12:51
Closed as this appears to be fixed.

**Closed by juliemturner** 2020-04-06 12:51 UTC
Labels: area: content, status: answered, type: bug
