### ISSUE TITLE
 Extra height padding on the video or content viewer

### ISSUE THREAD

**Issue by hadwinfung-woodside** [pnp/custom-learning-office-365#332] opened 2020-08-05 06:51 UTC
## Describe the bug

Extra height padding on the video or content viewer. Users are thinking there are still content at the bottom of the page, and are scrolling to see pages and pages of white space.

### To Reproduce

Navigate to any video or content page (especially one with not not much content), notice the position of the scroll bar. If you scroll down using to the bottom of scroll bar, you will notice pages and pages of white space.

Sample video page - Six Simple Steps > Welcome to Microsoft 365
[SiteName]/SitePages/CustomLearningViewer.aspx?cdn=Default&subcategory=9bde32c3-2f0b-4201-b4a3-74cef2c8f61d

### Expected behavior

Not expecting so much extra padding/white space at the bottom of the page.

### Screenshots

[Noticed the extra height is set at the DIV level]
![CustomLearningViewer_ExtraHeightPadding](https://user-images.githubusercontent.com/66932230/89378161-d6756100-d725-11ea-9abe-5981253be7d1.JPG)

[This is just at the end of the video player, notice the position of the scrollbar & the extra white space at the bottom]
![CustomLearningViewer_ExtraHeightPadding2](https://user-images.githubusercontent.com/66932230/89378193-e4c37d00-d725-11ea-96f8-1c0c621cb228.JPG)

### Learning Pathways version number

4.1.2.0

### Additional context

Noticed this issue after upgrading from 4.0.0.0 to 4.1.2.0

**Comment by juliemturner** [comment] 2020-08-05 11:38
This is a duplicate of #171.

**Closed** 2020-08-05 11:39 UTC
Labels: area: content, status: duplicate, type: bug
