### ISSUE TITLE
The CustomLearningWebPart has not been properly configured and you do not have Owner rights to complete the operation. Please contact the site administrator

### ISSUE THREAD

**Issue by StanislavO365** [pnp/custom-learning-office-365#18] opened 2019-03-27 15:31 UTC
Hello,
After installing the Custom learning for Office 365 in SharePoint, we have faced 1 annoying issue that prevents users from using the portal.
When users try to use the learning portal, the sometimes receive the error:
“The CustomLearningWebPart has not been properly configured and you do not have Owner rights to complete the operation. Please contact the site administrator.”

Any ideas what can it be?
Side note: I have tried modifying the site (removed some web parts) before receiving the notification email.

**Comment by m3d0c** [comment] 2019-03-27 17:01
I have the same issue with this. I deployed the solution using my tenant admin account and this account can see the pages. I shared the link to one of the other owners to the site and she can see the page but when I use my normal account I get the same errors message as the web part is not configured. 

How would you configure the user access list? Is this is not based on the SharePoint groups for the site collection its deployed to.

**Comment by juliemturner** [comment] 2019-03-27 21:52
Yes it is based on SharePoint user groups.  Did you do a manual installation or use the PnP Provisioning service?  The latter should configure everything for you but you will need to place users in the right groups.  All users that should view the custom learning web part should be in the visitors group.  Any users that you want to administrate content need to be at least in the members group but also could be in the owners group, your choice.

**Comment by m3d0c** [comment] 2019-03-28 09:59
Thanks for the feedback @juliemturner 

Yes I did a manual install and these are the steps I followed. 
1. Downloaded the repository from here.
2. Installed the app in our existing app catalog
3, Had to modify the PowerShell(or took sections from it to create a new PowerShell script). So I connect to my tenant admin (xx-admin). Get the appcatalog. Create the PnPStorageEntitiies successfully and then create the pages on the site to deploy as our existing comms site is on "/teams/" path.
4. Ran the script as SharePoint admin using my admin account. 
5. I have added my normal account in the default owners groups same as the other user in my team but I cannot see the page and she can

Any help would be appreciated.

**Comment by juliemturner** [comment] 2019-03-28 20:21
If you have at least 1 user able to see the webpart successfully then it would appear you have it properly configured. What is a bit hard to understand is what webpart you're trying to look at. Can you tell me the name of the page that you're looking at, CustomLearningAdmin or CustomLearningViewer? 

I can't come up with a good reason as to why you're having issues based on what you're describing. If you could paste in any errors you get from the browser's debug console that would maybe point me in the right direction to help you.

**Comment by StanislavO365** [comment] 2019-03-29 12:36
After some experimentation I think I have figured out where the problem is coming from.
Admin user had no issue in viewing the page and using all the web parts. The problem was present only for regular users, and it appeared irregularly.
Also, thing to note: I was using custom SharePoint groups with slightly modified custom permissions.

After collaboration with MS support, we did find out that problem is in the permissions. It said that two permissions are missing: "Browse directories" and "Browse user information".
I did check the permissions, and default ones and custom ones had the same thing: “Browse directories” was disabled, and "Browse user information" was enabled.

In the end I have created a new site using the provisioning service and deleted the old one. The new site works fine (no changes made in the new site).

**Comment by m3d0c** [comment] 2019-03-29 12:56
Hi @juliemturner 

I have enclosed the console log from our version of IE (Version 11.379.17763.0) but just by trying other browsers (Chrome & Edge) it works for me and other users as well. Its only IE that fails

![IEConsole](https://user-images.githubusercontent.com/34741272/55233830-a066c980-5221-11e9-80c9-f5880c166fc8.png)

The issue is that one of the site owners can see it in all browsers but based on the console output for IE, hopefully you can provide more insight?

**Comment by drewdevo** [comment] 2019-04-15 23:28
I've noticed that when browsing to the Learning site from a machine not joined to our domain that the pages will render the message, "The CustomLearningWebPart has not been properly configured and you do not have Owner rights to complete the operation. Please contact the site administrator."

I've tried with 2 different tenants (DEV and PROD) with regular user accounts and Global Admin, SCA accounts. This was provisioned from the Provisioning Service site. Am I overlooking something? Permissions?

**Comment by juliemturner** [comment] 2019-04-16 00:26
All users that need to access the custom learning web part must be in the viewers group of the site collection that is the home for custom learning (ie where the admin page is and the custom lists)

**Comment by KCuenco123** [comment] 2019-04-16 01:29
Hi Julie,

I've successfully deployed this site collection and even after adding Read or View access to everyone in the company on the top site collection, we still get "The CustomLearningWebPart has not been properly configured and you do not have Owner rights to complete the operation. Please contact the site administrator." on IE 11 browser.

Thanks,
Karen

**Comment by batilcl** [comment] 2019-04-16 08:43
I can confirmed this can only be reproduced on IE 11. On the same computer Edge and Chrome works fine.

Deployed a few sites, its all the same, only on IE11.
![custlearn](https://user-images.githubusercontent.com/28776353/56195047-be785a80-6066-11e9-9854-a90391ee467e.png)

**Comment by dpc80111** [comment] 2019-04-16 13:02
When will this be corrected?

Dave Clay
SharePoint Administrator
O 303.752.6252
David.Clay@uchealth.org<mailto:David.Clay@uchealth.org>

**Comment by juliemturner** [comment] 2019-04-16 13:25
Yes there is a known issue on IE11, it will be fixed in a future release.

**Comment by dpc80111** [comment] 2019-04-16 13:35
DO you have an ETA on the fix?

Dave Clay
SharePoint Administrator
O 303.752.6252
David.Clay@uchealth.org<mailto:David.Clay@uchealth.org>

**Comment by dpc80111** [comment] 2019-04-18 15:22
I believe the IE issue remains. I removed old site, provisioned new site and IE 11 still throws the error:

The CustomLearningWebPart has not been properly configured and you do not have Owner rights to complete the operation. Please contact the site administrator.

Dave Clay
SharePoint Administrator
O 303.752.6252
David.Clay@uchealth.org<mailto:David.Clay@uchealth.org>

**Comment by juliemturner** [comment] 2019-04-18 16:03
And you're saying that if you go to the same page in Chrome it works fine?

**Comment by dpc80111** [comment] 2019-04-18 16:06
That is correct, NO error in Chrome

Dave Clay
SharePoint Administrator
O 303.752.6252
David.Clay@uchealth.org<mailto:David.Clay@uchealth.org>

**Comment by batilcl** [comment] 2019-04-23 09:49
> And you're saying that if you go to the same page in Chrome it works fine?

@juliemturner I can repro this on IE 11 and works fine in any other browser. I can help to share more if required.

**Comment by juliemturner** [comment] 2019-04-23 12:56
It has been confirmed by  multiple people that this issue is closed.  The last person did not have the updated web part in their site collection.  From site contents, if you select 'Details' for the Custom Learning for Office 365 app, you should see verison 2.0.11.  If you do not then you do not have the latest version of the code.  Please verify that version 2.0.11 is installed in your tenant app catalog first.  If not download it from this repository and upload it into the tenant app catalog, which will upgrade the solution.  Click "Deploy", and optionally check in the solution making sure that the version is updated.  Then navigate to the site collection and update the version there.  Also please make sure you clear the cache in IE.  If you're still experiencing issues please create a new issue.

**Closed** 2019-04-23 21:04 UTC
Labels: bug

**Comment by MichaelMontMoore** [comment] 2019-08-19 17:02
I am seeing this today with some IE 11 users, but not all.  It does not appear to be an issue in Chrome.  We have already deployed version 2.0.13.0, Release Date May 2019.

**Comment by juliemturner** [comment] 2019-08-19 17:26
@MichaelMontMoore -- The current release is 2.0.17.  If you could please update to that version and then if you're still having issues please submit start a new issue.
