### ISSUE TITLE
Display Language Issue in Learning Pathways

### ISSUE THREAD

**Issue by chandni-agarwal** [pnp/custom-learning-office-365#562] opened 2021-07-15 13:36 UTC
I have updated the learning pathways to v4.3 and turn off translation with English as default. But still not the News and Content not in English. Can someone guide how to resolve this?

I have also checked the signed in user's language and language settings for the site. But everything is fine there

**Comment by jellis-thrive** [comment] 2021-07-15 14:11
Hello @chandni-agarwal 

Is the content you are trying to look at in English, default Microsoft content that comes with Learning Pathways automated deployment, or content that you made?

If it is content you made, you have to translate it yourself and align it with the English page for viewing. More information about that is available here:
https://docs.microsoft.com/en-us/office365/customlearning/custom_translate_pl_ml

I see that you have also checked the user's profile and language settings; this is also required.

**Comment by chandni-agarwal** [comment] 2021-07-15 14:20
Hi @jellis-thrive,

It is the content coming from Microsoft.

**Comment by jellis-thrive** [comment] 2021-07-15 14:24
Hello @chandni-agarwal 

In the top right of the page, there is a Language tab with a drop down you can click to change the language. What does it say for the user you are working with?

**Comment by chandni-agarwal** [comment] 2021-07-15 14:25
The language tab says "English"

**Comment by dcashpeterson** [comment] 2021-07-15 15:10
The language picker in the page does not affect the language the learning pathways web part shows up in, it's all driven off the MUI, you can mostly tell what the user's MUI is because the OOB SharePoint content will be translated to whatever language the user's MUI is set to... that comes from the Delve profile first, whatever the top language is, then if they have none set up it falls back to whatever language they have set in the browser (this is a good option for testers because it's faster and easier to set your language in the browser and if you have no language set int he browser it would fall back to the default language for the site.  That's how the web part knows what language it's supposed to display. You can see more about this in Issue #562 https://github.com/pnp/custom-learning-office-365/issues/562#issuecomment-880739087

**Comment by chandni-agarwal** [comment] 2021-07-16 13:10
Hi @dcashpeterson, checked the language in delve as well. Still the same issue

**Comment by chandni-agarwal** [comment] 2021-07-19 04:49
@jellis-thrive , any suggestions on same please

**Comment by jellis-thrive** [comment] 2021-07-19 13:11
Hello @chandni-agarwal - ""Stel vragen en vraag hulp" is Dutch; if your user drop down for the default content is English, the best next step would be to check all of the places where the person you are trying to help may have their language set to Dutch. Please take screenshots of these settings and provide them here during your review, including a screenshot of the English page showing the Dutch text.

**Comment by chandni-agarwal** [comment] 2021-07-19 13:51
Hi @jellis-thrive ! 

![image](https://user-images.githubusercontent.com/23003280/126169712-833e46b7-9469-4081-bc29-dc6871e1dcd1.png)

![image](https://user-images.githubusercontent.com/23003280/126170554-cd3dbf55-356f-4015-9199-5b144c7379ad.png)

Does this help?

**Comment by jellis-thrive** [comment] 2021-07-19 14:01
Hi @chandni-agarwal - yes, it does help thank you! Could you please also check / screenshot the user's Profile language?

https://support.microsoft.com/en-us/office/change-your-personal-language-and-region-settings-caa1fccc-bcdb-42f3-9e5b-45957647ffd7

**Comment by chandni-agarwal** [comment] 2021-07-19 14:10
Hi @jellis-thrive, attaching same

![image](https://user-images.githubusercontent.com/23003280/126173535-9536e9c0-4b81-468a-86a8-6d77a9a941f2.png)

**Comment by chandni-agarwal** [comment] 2021-08-23 05:23
hi @jellis-thrive, any suggestions?

**Comment by dcashpeterson** [comment] 2021-08-23 17:27
@chandni-agarwal  I did some additional digging into this. It looks like a duplicate of #566. It appears to be an issue with the provisioning service.You could also post to the provisioning service issues list. https://github.com/SharePoint/sp-provisioning-service/issues.  I am going to close this issue and leave the other one to ensure we follow up on it. 
Duplicate of #566

**Closed by dcashpeterson** 2021-08-23 17:27 UTC
Labels: status: duplicate, type: question, status: answered, area: web part
