### ISSUE TITLE
Truncation of content when in mobile / responsive view

### ISSUE THREAD

**Issue by timwalwyn** [pnp/custom-learning-office-365#324] opened 2020-07-29 18:39 UTC
## Describe the bug

When rendering content on a mobile device, truncation occurs ~couple of of pages down.  There appears to be a hard limit on the amount of content that can be displayed both within the SharePoint mobile app or mobile browser.  This is using the default content (e.g. SharePoint -> Quick Start -> Create a site) where content is simply cut off near the end of the page.

### To Reproduce

Load the above page in a mobile responsive view.

### Expected behavior

All content embedded within the page in the playlist should render.

### Screenshots

![learningPathwaysMobile](https://user-images.githubusercontent.com/33627084/88839481-09be6a00-d1d3-11ea-8d0e-c3ec98ce0076.PNG)
![learningPathsDesktop](https://user-images.githubusercontent.com/33627084/88839484-0a570080-d1d3-11ea-9d5b-ddeef6f2b19c.PNG)

### Learning Pathways version number

3.0.0.0

### Additional context

N/A

**Comment by juliemturner** [comment] 2020-07-29 20:10
It's not entirely clear but I think you're saying this is the first "page" or asset of the `Create a Site` playlist?  If that is the case, can you try moving to the second "page" and then back to the first page and see if that solves the issue? If so, then this is a duplicate of issue #171.

**Comment by juliemturner** [comment] 2020-09-01 20:50
Closing this issue for lack of activity.  If you are still experiencing problems, please feel free to open a new issue and reference this one. Thanks!

**Closed by juliemturner** 2020-09-01 20:50 UTC
Labels: area: content, status: details needed, type: something isn't working
