### ISSUE TITLE
Broken link in  Learning Pathway content

### ISSUE THREAD

**Issue by ChristopherCarlisle** [pnp/custom-learning-office-365#602] opened 2021-11-01 15:13 UTC
## Describe the bug

On the Recommended Playlist -> Create Impactful Content Together : There is a broken link to the OneDrive Quick Start.pdf. It returns 404, File not Found.

### To Reproduce

Click the link located on the bottom of the page at Recommended Playlist -> Create Impactful Content Together. (.../CustomLearningViewer.aspx?cdn=Default&playlist=fe736497-1a7c-4397-9963-17aab7e64557&asset=ba05d4f5-a174-4879-b1a1-0c6f77c1396b)

### Expected behavior

I believe the correct document is located at https://resources.techcommunity.microsoft.com/wp-content/uploads/2018/11/MS_Office_Quickstart.OneDrive.pdf

### Learning Pathways version number

4.1.4.0

![Capture3](https://user-images.githubusercontent.com/85195010/139694668-9a67fc3b-a601-420c-b9be-af88649ac401.JPG)
![Capture1](https://user-images.githubusercontent.com/85195010/139694679-0db1d217-cc44-4558-a7dc-e65fd9a15f07.JPG)
![Capture2](https://user-images.githubusercontent.com/85195010/139694683-32829f2c-5346-4df4-9edd-c9ce38adb487.JPG)

**Comment by dcashpeterson** [comment] 2021-11-01 15:17
Hello @ChristopherCarlisle this is a duplicate of #535 This is an issue with the content and have passed it on to the content team.

**Closed** 2021-11-01 15:18 UTC
Labels: status: duplicate, type: something isn't working
