### ISSUE TITLE
 M365 Learning Pathways Blank Homepage & Products Pages

### ISSUE THREAD

**Issue by cpc-volpep** [pnp/custom-learning-office-365#858] opened 2024-10-31 17:06 UTC
>**PROVISIONING NOTE**: If you are having issues with the SharePoint look book while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the SharePoint look book to [SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues).

>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) guidance before submitting your bug.

## Describe the bug

We are currently experiencing an issue where every couple of weeks our Learning Pathways homepage and product pages do not display any of the product tiles or their assets. We are able to resolve this by going to the admin page and hiding or displaying a product followed by reverting the change. For example, when I had to fix the issue today I toggled off the Microsoft Word section then toggled it back on -- after this is performed all of the product tiles begin displaying again and the page loads fine for everyone. 

We see the behavior consistent across several test users/machines, so it doesn't seem to be an isolated issue. 

### To Reproduce

I don't have great steps for reproducing since it will just end up in this "blank state" after a couple of weeks. Then I will resolve it by toggling a product tile off and back on again and the issue won't appear again until a couple weeks in the future. 

### Expected behavior

Expected behavior is just a normal load.

### Screenshots

Broken: 
![image](https://github.com/user-attachments/assets/2a3d48bc-1578-4735-bef8-c2774cf73783)

Fixed, after toggling a product tile on and off:
![image](https://github.com/user-attachments/assets/fdf40cd4-825e-4b79-a8ac-aaeb38300f7f)

### Learning Pathways version number

Version 5.0.0.4

**Comment by dcashpeterson** [comment] 2024-10-31 17:23
@cpc-volpep we didn't see that behavior in any of our V5 testing and without reproduction steps or errors I can't really do any troubleshooting. What it sounds like though is that Learning Pathways isn't being hit very often and that the cache is expiring and needs to be recreated or that it is having trouble creating the cache. It is blank because the cache hasn't finished, which also explains why it works after you show/hide something.

1. Question: Are you using a custom content pack?
3. Suggestion: Turn off any languages you are not using. If you installed through the LookBook and are only using an English site then you have 9 caches for languages you are not using being created.
4. Suggestion: The next time you see a blank page look in the developer tools in the console and see what the error is. Anything Learning Pathways related will have a 🎓 emoji next to it. Take a screenshot and provide it here so I can see what the issue is. My guess is that it can't access the cache.

**Comment by cpc-volpep** [comment] 2024-10-31 17:29
@dcashpeterson thanks so much for the quick response. 

1. I will have to confirm whether we are using a custom content pack -- forgive my not knowing, I helped install this tool initially about 4 years ago and update it regularly but don't do much of the maintenance or administration for playlists, custom content etc. 
2. I'm blanking on whether I installed initially via LookBook. How do I turn off languages? 
3. I will certainly take a look at dev tools next time the issue pops up and I can provide details here if I find anything. 

Thanks again!

**Comment by dcashpeterson** [comment] 2024-11-01 14:10
@cpc-volpep you can turn off the languages you are not using if you go to Site Settings > Language Settings and then just remove the languages you are not using. I am going to close this issue for now and if you see it again and have more details you can reference this issue.

**Closed by dcashpeterson** 2024-11-01 14:10 UTC
Labels: status: details needed, type: something isn't working
