### ISSUE TITLE
Add support for the Language German

### ISSUE THREAD

**Issue by nicht01** [pnp/custom-learning-office-365#63] opened 2019-05-21 14:40 UTC
#### Category

- [x] Question
- [ ] Typo
- [ ] Bug
- [x] Additional article idea

Im really happy to see this solution, because it allows us to use up to date content and filter and customize it,

We have one issue why we currently cannot use this solution, because we are forced to provide trainings also in German language. I have found all this trainings in German, but im not able to address them in O365 Custom Larning.

I mean the content is there, the custom webpart is there, we just miss a connection. 

For me it even wouldnt be an issue if i have 2 sites (one english and one german)

So i would really appriciate it if this also would Work for the German Language.

**Comment by peterjkrebs** [comment] 2019-05-21 16:35
Thanks for the feedback and suggestions. We plan on rolling out multilingual support for these nine languages in CY19 Q3:
Chinese (Simplified)
Dutch (Netherlands)
French
German
Italian (Italy)
Japanese (Japan)
Portuguese (Brazilian)
Russian (Russian)
Spanish

**Comment by nicht01** [comment] 2019-05-22 06:24
That sounds great. Awesome!

Is there a possibility to get early access in a kind of preview to this?

**Comment by juliemturner** [comment] 2019-05-28 15:13
Duplicate of #15

**Closed** 2019-06-13 17:10 UTC
Labels: question
