### ISSUE TITLE
Videos in MLPs are not loading - reference error 

### ISSUE THREAD

**Issue by Take4aWalk** [pnp/custom-learning-office-365#769] opened 2024-01-24 12:02 UTC
>**PROVISIONING NOTE**: If you are having issues with the SharePoint look book while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the SharePoint look book to [SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues).

>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) guidance before submitting your bug.

## Describe the bug

Any Video of the standard MLPs do not show up - any reference error

### To Reproduce

Try to do MLP "Microsoft Teams" for example - first step is "Teams Quick Start" and "What is Microsoft Teams" there should show up a video which wont be presented

### Expected behavior

The video should load and shouldbe playable

### Screenshots
below you can take a look at the error which shows up instead of the video

![image](https://github.com/pnp/custom-learning-office-365/assets/157599958/16f1ee46-6262-4b8e-82f1-d1c6cc649363)

### Learning Pathways version number

>Please share the version number of learning pathways in your tenant app catalog.
App is 4.4.0.0

### Additional context

>Add any other context about the problem here.

**Comment by dcashpeterson** [comment] 2024-01-24 12:04
@Take4aWalk  this is a duplicate of #767. Please keep an eye on that issue when the issue is resolved. Closing this one as a duplicate

**Closed by dcashpeterson** 2024-01-24 12:04 UTC
Labels: type: something isn't working
