### ISSUE TITLE
Prerequisites are not fulfilled AppCatalog rights 

### ISSUE THREAD

**Issue by HN5** [pnp/custom-learning-office-365#124] opened 2019-09-19 13:35 UTC
#### Category

- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Trying to provision Microsoft 365 Learning Pathway on a Dev tenant.
Account used is global admin + primary/admin on AppCatalog site
AppCatalog is present on my tenant since 3 month and i have no issue with other Apps such as SPFx webPart 
I see Application provisionned on AAD Apps after consents done ( SharePointPnP.ProvisioningApp.Site + SharePointPnP.ProvisioningApp.Tenant )
I test with an other account : same result

#### Observed Behavior

I have the following message when i try to provisiong the M365LP :

_Prerequisites are not fulfilled
Current configuration of your SharePoint Online tenant does not satisfy some of the pre-requirements to provision the selected package.

Here are further details about the missing prerequisites:

In order to provision the template you need to have Full Control permissions on the App Catalog in your tenant. Please, configure the App Catalog security settings, and try again.
Please address the findings and try again._

#### Questions

**Is there any steps i missed ?
Any guidance to provision this site ?**

Thx for your help

**Comment by juliemturner** [comment] 2019-09-19 13:59
Duplicate of #122 

@HN5 -- please see my response in issue 122.  Thanks.

**Comment by Lee-Myhre** [comment] 2019-09-23 18:27
Hi, @HN5 and @juliemturner : This issue appears to still be happening. The "original" topic has been closed prematurely, which is why I am commenting on this thread instead.
Any updates/timeframes for this fix? All of us who have been trying to deploy Learning Pathways and have been unable to do so, I have been trying since Friday Sept 13 to resolve this with no luck.

**Comment by juliemturner** [comment] 2019-09-23 18:33
@Lee-Myhre -- The issue is closed because it's a duplicate, it's also closed because we have no way of supporting issues with the provisioning service. I have been informed that the fix was rolled out, if you are still experiencing an issue please submit your issue to the sp-dev-docs repository where they can adequately provide you support. https://github.com/SharePoint/sp-dev-docs/issues

**Closed** 2019-11-16 19:15 UTC
Labels: duplicate
