### ISSUE TITLE
Video does´nt play in Learning pathways in Teams, but in the web. The video  is posted as a link från Stream, and I am the owner. Neither me, nor other people in the organisation kan play the video. 

### ISSUE THREAD

**Issue by PiaStider** [pnp/custom-learning-office-365#799] opened 2024-06-12 07:39 UTC
>**PROVISIONING NOTE**: If you are having issues with the SharePoint look book while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the SharePoint look book to [SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues).

>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) guidance before submitting your bug.

### To Reproduce

>Steps to reproduce the behavior

### Expected behavior

>A clear and concise description of what you expected to happen.

### Screenshots

>If applicable, add screenshots to help explain your problem.

### Learning Pathways version number  4.1.4 (Adviced not to update due to risk for problems... )

>Please share the version number of learning pathways in your tenant app catalog.

### Additional context

>Add any other context about the problem here.

**Comment by PiaStider** [comment] 2024-06-12 07:43
Tried to describe the problem in the form, but it does´nt stick... 😒 I got the issue from a user, and both me and my colleague experience the same problem. I tried restarting Teams, no difference. There are several similar links posted at the same page not working. 
![image](https://github.com/pnp/custom-learning-office-365/assets/157601940/c5b746c2-818e-48a0-b61b-e8e68c1f527d)

**Comment by dcashpeterson** [comment] 2024-06-12 11:19
closed as duplicate of #798

**Closed by dcashpeterson** 2024-06-12 11:19 UTC
Labels: type: something isn't working
