### ISSUE TITLE
Custom Learning Pathways not showing

### ISSUE THREAD

**Issue by rickvana** [pnp/custom-learning-office-365#768] opened 2024-01-24 09:13 UTC
## Describe the bug

When we add custom content to the M365 pathways it is not showing up on both the training page and inside a learning route. 

### To Reproduce

We create custom content within a learning route, but it doesn't show up. Also doesn't show when we empty our cache. 

### Expected behavior

We expect the learning route to be visible when we create it.

### Screenshots

![image](https://github.com/pnp/custom-learning-office-365/assets/61792858/a2de3bc4-0c9b-4192-b764-1b3cd903e912)
![image](https://github.com/pnp/custom-learning-office-365/assets/61792858/b4f7fc45-3f06-4cfd-8a2c-7a59e1f1e058)
![image](https://github.com/pnp/custom-learning-office-365/assets/61792858/c1f97679-bd90-49fe-be31-8fb24a0304e7)
![image](https://github.com/pnp/custom-learning-office-365/assets/61792858/a17b4aa2-f850-42d4-b2b1-3689681cac8b)

### Learning Pathways version number

4.4.0.0

**Comment by dcashpeterson** [comment] 2024-01-24 09:41
Hi @rickvana, I am not able to reproduce this with the instructions that you provided but I do have a guess.

Can you please tell me the default language of your Learning Pathways site? To do this go to Settings > Site Information > View All Site Settings >  Site Administration 
 | Language Settings. My guess is that the default language for the site is English.

Then check the custom content (sub-categories, playlists, and assets) you are trying to create. Do you have title, description, etc for all the fields for the default language? If not that is the problem, add an English translation and they should show up.

Your Learning Pathways site was provisioned through the [LookBook](https://lookbook.microsoft.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239). As a result the default language for the site is set to English (see system requirements). You always need to have content in the default language for the site in order for it to be displayed.

Give that a shot and let us know if that fixed the issue.

**Comment by dcashpeterson** [comment] 2024-01-25 13:33
@rickvana great to hear it. Closing this as resolved.

**Closed by dcashpeterson** 2024-01-25 13:33 UTC
Labels: type: something isn't working
