### ISSUE TITLE
Problem displaying videos

### ISSUE THREAD

**Issue by moca-dev** [pnp/custom-learning-office-365#770] opened 2024-01-25 13:28 UTC
Hi, since yesterday we've had an error message when displaying the training pages 👍 

**An error occurred while processing your request. 
Reference #30.3ff63717.1706189248.2a194666**

![image](https://github.com/pnp/custom-learning-office-365/assets/59876859/dee39e96-f49a-4ff6-8c1b-f5c81b23bf19)

I can't find the explanation for the error code. 
Do you have the same problem? Have you been able to solve it and if so, how? 
Thank you in advance for your help.

**Comment by dcashpeterson** [comment] 2024-01-25 13:32
@moca-dev this is a duplicate of #767. Please keep an eye on that issue when the issue is resolved. Closing this one as a duplicate

**Closed by dcashpeterson** 2024-01-25 13:32 UTC
Labels: type: question
