### ISSUE TITLE
SharePoint playlist - content for create and share files 

### ISSUE THREAD

**Issue by pb762** [pnp/custom-learning-office-365#192] opened 2020-01-21 18:49 UTC
>**PROVISIONING NOTE**: If you are having issues with the provisioning service while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the provisioning service to [https://github.com/SharePoint/sp-dev-docs/issues](https://github.com/SharePoint/sp-dev-docs/issues).

**Describe the bug**
In the SharePoint playlist "Share and Sync with SharePoint" the first asset title is " Create and share files in a library" but the content seems to be related to "Create a page"?

**To Reproduce**
1. Go to SharePoint
2. Click on Share and Sync with SharePoint playlist
3. Scroll down to Content of the first asset "Create and Share files in a library" -
4. the steps are to create a page instead.

**Expected behavior**
Steps to create and share files

**Screenshots**
![image](https://user-images.githubusercontent.com/59031625/72833165-3ad24680-3c54-11ea-854a-d55db2cfea61.png)

**Learning Pathways version number:**
Please share the version number of learning pathways in your tenant app catalog. 3.0.2

**Additional context**

**Comment by pb762** [comment] 2020-01-21 18:51
Ah just noticed that this was already opened on Dec 16th. By when is it expected to be resolved?

**Comment by juliemturner** [comment] 2020-01-21 19:12
Duplicate of #165

**Comment by juliemturner** [comment] 2020-01-21 19:13
I, unfortunately, do not own the content and can't speak to when this will be resolved.

**Closed** 2020-02-13 17:03 UTC
Labels: Content, bug
