### ISSUE TITLE
 Edits to a custom category/playlist/Asset within Microsoft 365 Learning Pathways doesn't hide properly after its saved.

### ISSUE THREAD

**Issue by lamargardner565** [pnp/custom-learning-office-365#726] opened 2023-03-27 17:38 UTC
ISSUE: 
Editing an Asset within LP site causes all LP content to be viewable to all users, regardless of view settings.

DESCRIPTION: 
When a playlist is edited within the LP site, once the asset is saved, all tiles in the MS Learning Pathways solution is viewable to site visitors, even where many of those assets should be hidden.

APP DETAILS:
Microsoft 365 Learning Pathways version 4.3.1.0, release date February 2023

![image](https://user-images.githubusercontent.com/105717854/228021161-9b527f33-c520-4426-8151-dbc4b515f64f.png)

 

STEPS TO REPRODUCE:
1.	Ensure the LP Home page, or [Learning Pathways Viewer page], is displaying the correct tiles

 
![image](https://user-images.githubusercontent.com/105717854/228021193-0e783d97-f74f-4504-9a4b-8f4283d0120f.png)

2.	Navigate to the [CustomLearningAdmin]) Page in LP, select a subcategory and select a Playlist within that subcategory

![image](https://user-images.githubusercontent.com/105717854/228021224-e54061ff-5aeb-4658-a79a-2c38b598438a.png)

 
3.	Scroll down to Playlist Assets and make a change and revert (in order to trigger/unghost the Save Asset button). In the example below, I changed “Teams” to “Teamz” and back to “Teams” to allow a new save, just for testing. Note that any change/addition/deletion, whether reverted or kept, will introduce this issue.

![image](https://user-images.githubusercontent.com/105717854/228021275-132bc321-bf63-4e2d-8ca9-901512d859fe.png)

 
4.	Navigate back to the Home/HUB page, or [Learning Pathways Viewer page], and note the web part now displays ALL content, even though the admin page indicates they should be hidden.

 
![image](https://user-images.githubusercontent.com/105717854/228021318-4b63862a-247d-40c7-9165-0c3fa5755f52.png)

WORKAROUND:

1.	To remediate this issue, navigate to the [Customer Learning Admin] page in LP and toggle the visibility of a subcategory to trigger the admin page to auto save. Note this is not a viable workaround solution, as customers will be able to view all hidden content until they reload the page.

 
![image](https://user-images.githubusercontent.com/105717854/228021351-388a677f-14cd-4669-bfe7-564da0d2d942.png)

2.	The Home tiles then display the correct viewable content:

![image](https://user-images.githubusercontent.com/105717854/228021402-58b07794-5d4c-4d91-9a5c-ce78e92ec2b2.png)

### Additional context

>Add any other context about the problem here.

Can you please provide context to why this is happening?  Is this normal behavior?

**Comment by lamargardner565** [comment] 2023-03-28 15:29
Thank you!
________________________________

**Comment by v-prigunasek** [comment] 2023-03-30 17:51
Hi @dcashpeterson ,

I was able to reproduce the issue from my end. Whenever we edit an asset in a subcategory, the hidden subcategories become visible in the [Learning Pathways Viewer page] and we have to toggle the visibility button on the hidden subcategory to hide it again.  Can you please confirm whether this is an expected behavior? Thanks!

**Comment by juliemturner** [comment] 2023-03-30 20:15
Yep, I can confirm this is a bug. The interim fix is to toggle the hide/show for just one category or playlist and that will fix all the settings.

**Comment by lamargardner565** [comment] 2023-03-30 20:46
Thank you for the update.  Is this bug getting worked on?  Is there a time line when this will be fixed or is a new current solution being worked on. I am afraid that my customer wil loose all there content if this solution has to get re deployed for there environment.  Any context is greatly appreciated.

V/R
Lamar R. Gardner
Cloud Solution Architect – Engineering
Microsoft Federal | Business Applications
SharePoint | Dynamics 365 CRM
E: ***@***.******@***.***> | E: ***@***.******@***.***>
[Graphical user interface, application  Description automatically generated]

**Comment by lamargardner565** [comment] 2023-03-30 20:46
Also,  can you please confirm that this is for both content packs and non content packs witbh out of the box custom content categories?

V/R
Lamar R. Gardner
Cloud Solution Architect – Engineering
Microsoft Federal | Business Applications
SharePoint | Dynamics 365 CRM
E: ***@***.******@***.***> | E: ***@***.******@***.***>
[Graphical user interface, application  Description automatically generated]

**Comment by juliemturner** [comment] 2023-03-31 14:52
@lamargardner565 It's not a great idea to respond to github notifications via email because it ends up embedding PII in the repository so I would avoid that in the future if I were you. I've edited your comments to remove it.

The bug has been fixed, a PR has been issued, but has not been merged in. When it is this issue will automatically be closed so you will get a notification. I suspect it could happen next week at some point after it's reviewed.

You do not loose data when you update a SharePoint Framework package, you just need to update it.
The update is for the base software, content packs have no baring on how it works and is unrelated.

**Comment by lamargardner565** [comment] 2023-03-31 15:12
Thank you for the update as in the future I will refrain from replying to all.  Also, thank you for the update on the M365 LPs bug fix.  Have a great day.

V/R
Lamar R. Gardner
Cloud Solution Architect – Engineering
Microsoft Federal | Business Applications
SharePoint | Dynamics 365 CRM
E: ***@***.******@***.***> | E: ***@***.******@***.***>
[Graphical user interface, application  Description automatically generated]

**Comment by lamargardner565** [comment] 2023-04-17 12:55
Good morning,

I am checking in to see if there is a update on the this bug fix or maybe an approximate time when the final review will be completed?

V/R
Lamar R. Gardner
Cloud Solution Architect – Engineering
Microsoft Federal | Business Applications
SharePoint | Dynamics 365 CRM
E: ***@***.******@***.***> | E: ***@***.******@***.***>
[Graphical user interface, application  Description automatically generated]

**Comment by dcashpeterson** [comment] 2023-04-18 10:00
@lamargardner565 my apologies. I am the bottleneck here on the merge. I've been tied up with client work. I will get this merged in the next week or so.

**Comment by lamargardner565** [comment] 2023-04-18 10:37
Good morning and no worries.  Thank you for the update.

V/R
Lamar R. Gardner
Cloud Solution Architect – Engineering
Microsoft Federal | Business Applications
SharePoint | Dynamics 365 CRM
E: ***@***.******@***.***> | E: ***@***.******@***.***>
[Graphical user interface, application  Description automatically generated]

**Closed** 2023-04-20 13:31 UTC
Labels: type: bug, status: fixed, area: SPFx

**Comment by dcashpeterson** [comment] 2023-04-20 13:44
@lamargardner565  I have merged in the fix for this. You can update your package to the latest version.
