### ISSUE TITLE
[ENHANCEMENT] Sort playlists from the administration

### ISSUE THREAD

**Issue by JcBrabant** [pnp/custom-learning-office-365#316] opened 2020-07-27 09:18 UTC
I noticed the possibility to sort playlist in the webpart configuration. 
However I want to change it directly from the administration to apply this order in all webparts directly.

**Comment by juliemturner** [comment] 2020-07-28 20:39
Duplicate of #96

**Comment by JcBrabant** [comment] 2020-07-30 07:43
Hi, I understand the link, but it's really a duplicate as the enhancement is to manage it from the administration, not the webpart itself. 
Considering, we can add learning webpart in many pages, in many sites, and considering the lifecycle of the learning content, it could be really complicated to have this feature only on the webpart configuration, and not directly through the admin.

**Comment by juliemturner** [comment] 2020-07-30 11:32
Yes, it actually is because that enhancement request was a request to manage the sort from the admin web part.  Because we cache data every time the admin webpart makes any change customizing the sort at the admin level will add significant overhead because of how many permutations of how that sort needs to be remediated when the things change from the source and how things are customized per client. To address that enhancement request we decided that by limiting the scope of the sort, we actually provide more flexibility and have somewhat mitigated risk issues with applying the sort against a source dataset that has changed.

If you require more fine grained customization it is always your choice to use the custom content set feature to manipulate the source content exactly the way you want to, although you will then have to merge any changes that happen during quarterly updates manually, but this does allow you ultimate control.

I am happy to leave the enhancement request open to be considered sometime in the future.

**Closed** 2021-01-08 16:21 UTC
Labels: area: web part, status: duplicate, type: enhancement
