### ISSUE TITLE
Custom Assets still showing Header - any workarounds? 

### ISSUE THREAD

**Issue by mhomol** [pnp/custom-learning-office-365#676] opened 2022-06-23 02:41 UTC
## Describe the bug

I've seen other bugs about this already but they were closed (ie. #140) so I felt it best to just post a new item here.  

Essentially I've setup custom asset pages for a learning course but the site header is still showing up in my learning path viewport, like so:

![Screen Shot 2022-06-22 at 10 29 47 PM](https://user-images.githubusercontent.com/680566/175194799-5c4ae911-4d8a-4e9f-beba-1e992aafdeee.png)

I found [this article](https://sharepoint.handsontek.net/2021/01/24/hide-navigation-header-modern-sharepoint-pages/) around using the query string to override this, and in the above the asset link is using `?env=WebViewList`, but the best I'm getting is the hub nav going away but still not the site header.

### To Reproduce

Setup a custom playlist with a custom asset and choose to make a new page
Edit said page and set it to plain and put in some content.
_Optional_: Return to the asset and append `?env=WebViewList` to the URL
View the course somewhere on a page and see that the hub meganav is no longer rendering but the site header is showing up

### Expected behavior

Would be preferred for the header on the modern pages to hide when within a learning pathway viewport

### Learning Pathways version number

4.3.0.0

### Additional context

If there's any workaround like the query string idea, I'm all ears.  Or a web part that hides it even.  Just looking for direction, if nothing else.

**Comment by v-ashrirao** [comment] 2022-06-23 14:08
@mhomol, Thank you for reporting this. Please allow us some time, we will get back to you ASAP.

**Comment by mhomol** [comment] 2022-06-27 13:21
Yes, you're assumptions are 100% on point.

**Comment by dcashpeterson** [comment] 2022-07-05 09:55
@mhomol we are still trying to replicate the original issue. As for the screen shot you just posted that is out of the box SharePoint. It is designed to expand the viewing area of the page. It is not related to learning pathways.

**Comment by v-ashrirao** [comment] 2022-07-18 05:11
@mhomol, we tried steps which are given by you to reproduce this issue but unfortunately, we are unable to reproduce.
Can you please provide some more details regarding site setup and steps to reproduce so that we can reproduce this issue and assist you further?

**Comment by mhomol** [comment] 2022-07-18 21:09
Well this is awkward.  I can no longer replicate the issue I was having, despite having made no changes to any of my assets since posting this issue. Upon getting the above comment, I went to the same asset as my original screenshot above and this time, the site header was not displaying, as is intended.

![Screen Shot 2022-07-18 at 5 07 22 PM](https://user-images.githubusercontent.com/680566/179617507-1f50c24d-a885-4777-842c-75ede0761f41.png)

Could something have changed in the SharePoint core, based on a recent release, that would have fixed the issue since the time of my posting?

**Comment by v-ashrirao** [comment] 2022-07-19 07:38
@mhomol, we are not sure about what happened in backend, but glad to know that you are not facing this issue now. 
Please do let us know if we can close this issue now?

**Comment by dcashpeterson** [comment] 2022-07-19 08:28
@mhomol there could have been a change in the UI that caused a very specific issue with learning pathways and it was fixed. Thanks for letting us know and thanks for using Microsoft 365 learning pathways.

**Closed** 2022-07-20 11:22 UTC
Labels: status: details needed, type: something isn't working
