### ISSUE TITLE
Unable to access Custom Learning Admin 

### ISSUE THREAD

**Issue by corbettiain** [pnp/custom-learning-office-365#572] opened 2021-08-05 01:02 UTC
I'm unable to access the Learning Pathways Custom Learning Admin page: /sites/M365LP/SitePages/CustomLearningAdmin.aspx.  The page just hangs and doesn't load, so I can't view the pages and assets that are available.

## Describe the bug

Cannot open the Custom Learning Admin page  /sites/M365LP/SitePages/CustomLearningAdmin.aspx. 

### To Reproduce

Try to access the Custom Learning Admin page  /sites/M365LP/SitePages/CustomLearningAdmin.aspx. 

### Expected behavior

The Custom Learning Admin page should open.

### Screenshots

>If applicable, add screenshots to help explain your problem.

### Learning Pathways version number

>Please share the version number of learning pathways in your tenant app catalog.

### Additional context

>Add any other context about the problem here.

**Comment by dcashpeterson** [comment] 2021-08-05 10:20
@corbettiain unfortunately we will need some additional information to assist with this. Can you please add any errors you are receiving in the console, screen shots, version number, etc, per the template.

**Comment by corbettiain** [comment] 2021-08-05 22:30
Thank you Derek.  I'll add what detail I can, but I am not an admin for the whole organisation, I am just an owner of the Learning Pathways site.  I did find another issue that was raised that is I think the same issue: (https://github.com/pnp/custom-learning-office-365/issues/363)

Describe the bug
Cannot open the Custom Learning Admin page /sites/M365LP/SitePages/CustomLearningAdmin.aspx. The page just doesn't load up.

To Reproduce
Try to access the Custom Learning Admin page /sites/M365LP/SitePages/CustomLearningAdmin.aspx.

Expected behavior
The Custom Learning Admin page should open.

Screenshots

![image](https://user-images.githubusercontent.com/50722727/128429273-7a204303-1bf0-42ca-91c9-c123440ef39e.png)
If applicable, add screenshots to help explain your problem.

Learning Pathways version number
I'm not sure how to find that information.

Additional context
Add any other context about the problem here.

**Comment by dcashpeterson** [comment] 2021-08-09 10:41
@corbettiain Thank you for the additional information. Can you please check or have your admin check that the account that was used to set up learning pathways is a site collection admin on the tenant app catalog. The other thing for them to check would be the application registration and make sure that the application registration is still there and can read/write to SharePoint. Could you try to get a copy of the console and any errors you encounter when you are able to reproduce this error. I know you're not an admin. If you need instructions let me know. It's hard to diagnose issues from a screen shot so anything from the console would be helpful.

**Comment by corbettiain** [comment] 2021-08-10 22:44
Thank you @dcashpeterson.  I got a screenshot of the console from the Admin - he said the permissions are correct.  Let me know if it would be easier to get him to connect with you directly.

![Screenshot_10082021](https://user-images.githubusercontent.com/50722727/128944159-844435e9-e4ba-4f5c-9061-622e31c8d4ef.png)

**Comment by dcashpeterson** [comment] 2021-08-11 13:29
@corbettiain From the look of this error it looks like the tenant app property is set to a different site than the one you are trying to use. Does the playbook site still exist and are you using it? If it doesn't exist then you will need someone who can run PowerShell (SharePoint Admin) to change the property. If the playbook site exists then you should use that instead of this site. You can only have one Learning Pathways admin site per tenant. Here is a link about changing the URL of your site. https://github.com/pnp/custom-learning-office-365#changing-the-url-of-your-microsoft-365-learning-pathways-site 

Please let me know if you need anything else.

**Comment by corbettiain** [comment] 2021-08-15 23:15
Excellent!  Thanks @dcashpeterson - I will pass this back to the Admin.  Your help has been very much appreciated.

**Comment by dcashpeterson** [comment] 2021-11-03 10:36
Closed as answered. If you are still having an issue please create a new issue.

**Closed by dcashpeterson** 2021-11-03 10:36 UTC
Labels: status: answered, type: something isn't working
