### ISSUE TITLE
Unable to either create new categories or update existing category titles

### ISSUE THREAD

**Issue by techieSudeep** [pnp/custom-learning-office-365#307] opened 2020-07-16 15:55 UTC
>**PROVISIONING NOTE**: If you are having issues with the SharePoint look book while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the SharePoint look book to [SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues).

>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/master/webpart/DiagnosisPreCheck.md) guidance before submitting your bug.

## Describe the bug

We have created few categories prior to v4 and have realized we no longer have the ability to update Category titles or create new categories.  

### To Reproduce

Go to CustomLearningAdmin.aspx and try to change any category title or create a new category title.

### Expected behavior

Able to update Categories. 

### Screenshots

>If applicable, add screenshots to help explain your problem.

### Learning Pathways version number

v4.0.2

### Additional context

>Add any other context about the problem here.

**Comment by juliemturner** [comment] 2020-07-16 16:12
I'm sorry this is not a known or reproducible bug so you'll need to provide a little more context.. maybe a screenshot?

**Comment by techieSudeep** [comment] 2020-07-16 17:03
Please find the attached screenshot Julie. As you can see we currently do not have the option to update Category name or create new categories. From the screenshot you will notice some of the categories we are using as Abandoned, Get started, Scenarios, etc. Appreciate your help. 
![Category](https://user-images.githubusercontent.com/52350666/87700581-89c0ea80-c764-11ea-9eb1-5281a6a0cb78.jpg)

**Comment by Webritter** [comment] 2020-07-20 11:16
Hello, I have the same situation after upgrade to 4.0.2.0.

I'm not able to create a new sub categorie. 

After clicking on the "+" right from "Add new Subcategory" there will be no input field to enter text and a have mentioned a javaScript error in the console:

custom-learning-admin-web-part_6475f28479293715bd1e4fad7c814856.js:1 Message: TypeError: Cannot read property 'description' of undefined - CategoryHeadingDetail (render)

**Comment by juliemturner** [comment] 2020-07-20 12:42
@techieSudeep 
Your issue if you look at the category that is on the screenshot is that you're looking at abandoned playlists, that playlist because of changes to the manifests no longer is associated with a category/subcategory. You need to edit that playlists and choose a category/subcategory you want it to be in and then that section will go away.

If you had picked another category/subcategory then you would have seen the ability to add new subcategories, but you should deal with the abandoned one first.

**Comment by juliemturner** [comment] 2020-07-20 12:43
@Webritter - even though you have "same situation" I don't know that you do as you didn't provide any screenshots and your description doesn't match up to the issue the other person is reporting. I would suggest you start your own issue and please provide as much information as you can so I can help diagnose your issue.

**Comment by juliemturner** [comment] 2020-07-28 19:24
Going to close this issue as answered. If you're still having issues please feel free to open a new issue and reference this one by typing #307 and filling out the details of your issue.

**Closed by juliemturner** 2020-07-28 19:24 UTC
Labels: area: web part, status: answered, type: something isn't working
