### ISSUE TITLE
Playlist url not connecting for Docs.microsoft.com

### ISSUE THREAD

**Issue by KC-MyGitHub** [pnp/custom-learning-office-365#251] opened 2020-04-30 14:45 UTC
Attempting to create a PowerBI sub-category with playlist utilizing docs.microsoft.com url.  Why do I receive error that docs.microsoft.com refused to connect?

I get a similar issue connecting to a Stream Channel.

Is there something else I need to do to enable these sites for use within a playlist (MS Learning Pathways webpart)?

**Comment by juliemturner** [comment] 2020-04-30 15:09
Duplicate of #250

**Closed** 2020-04-30 15:09 UTC
Labels: area: custom content, status: duplicate, type: question
