### ISSUE TITLE
 NO mp4 videos work anymore 

### ISSUE THREAD

**Issue by luvsql** [pnp/custom-learning-office-365#862] opened 2024-11-06 20:18 UTC
We have many video playlists (mp4) that are links from Teams/SharePoint.  We have been viewing these for well over 1.5 years and now NONE of them work anymore.  We get the error "tenant.sharepoint.com refused to connect".  The videos run fine in SharePoint.
 

### To Reproduce

Click on any video that previously used to work and now none do.

### Expected behavior

The videos should play like they used to.  We have ALL of training videos here and now none of them work anymore. 
### Screenshots

>If applicable, add screenshots to help explain your problem.

### Learning Pathways version number

5.0.0.4

### Additional context

>Add any other context about the problem here.

**Comment by luvsql** [comment] 2024-11-06 20:28
Here are the errors from developer tools:

Refused to frame 'https://xxxxx.sharepoint.com/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'".

prefetch_8062fdba.js:1 invalid contentSourceFilter config
p @ prefetch_8062fdba.js:1Understand this warning
custom-learning-web-part_6a57f22c454c286fccf7.js:29 🎓 M365LP:InitService (setWebhookConfig) -- Tenant property 'MicrosoftCustomLearningWebhookConfig' has not been set.

**Comment by luvsql** [comment] 2024-11-06 20:36
I can also verify when these some of these videos were last viewed and have one that is October 16th.  This is 2 weeks after we upgraded to version 5.x so it can't be the upgrade.

**Comment by luvsql** [comment] 2024-11-06 20:52
More errors in the Edge Developer Tools.  Issue happens for many users on any browser.

Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received

**Comment by luvsql** [comment] 2024-11-06 21:09
I found one of the mp4 videos were viewed by a user properly yesterday at 2:29PM EST.  I have not changed anything tenant-wide this week.

**Comment by dcashpeterson** [comment] 2024-11-07 09:27
@luvsql can you please provide some additional details. Are the videos that are not working Microsoft provided assets or custom assets with video embedded. I just checked Home > Microsoft Teams > Teams Quick Start and the videos and Home > Outlook > Outlook Quick Start. I checked in Edge and in Chrome and the videos are working fine. Any additional details would be helpful.

**Comment by luvsql** [comment] 2024-11-07 12:55
These are our own mp4 videos that we have been compiling for years and have all worked up until 2 days ago.

These videos all work fine within teams desktop, teams browser, and SharePoint browser as they open by default in steam.  We store these videos in teams and SharePoint and use the copy link on the asset.  They do not work on this 365 learning site at all anymore.

**Comment by luvsql** [comment] 2024-11-07 13:27
When we try and open the video, you'll see in these screenshots that you have to scroll down at least 10 times to see the bottom so there is a weird thing happening with the frame that never happened 2 days ago.  It would show the frame like it does in Stream.
![How the video now renders in Pathways2](https://github.com/user-attachments/assets/d55fa02e-0eff-4bb8-b3c2-326c226217c2)
![How the video now renders in Pathways3](https://github.com/user-attachments/assets/791f82f3-b13d-42e3-905b-229e07655a08)
![How the video now renders in Pathways](https://github.com/user-attachments/assets/30bd5ef6-7b16-42a4-9ebb-cee223fd0482)

**Comment by dcashpeterson** [comment] 2024-11-07 13:37
@luvsql I was able to reproduce this. I have some good news and some bad news. What is happening is that the copy link generates a link that goes to a page with a viewer for whatever document it is (e.g. Word document, PowerPoint, or in your case MP4). If it didn't do this then the browser would try to download the file. The problem you are encountering is that Microsoft changed that viewer (obviously in the last few days) and made it not allow it's content to be Iframed. We have no control over the source code of SharePoint.

The good news is that if you are using MP4 files and they are available in SharePoint or Teams you can get an absolute path to the video and that is shown properly in Learning Pathways. To do this you can go to the Files tab in Teams (or a SharePoint Document library) select the document and then select details from the context menu. From there there is a property at the bottom called Path copy that value and you can use that for your custom assets.

This doesn't solve the problem of you have 150 existing custom assets. If you have a tool like ShareGate you can export the metadata from the CustomAssets list and edit the URLs for the custom assets and then update the data with ShareGate. If you don't have ShareGate you can do that same thing by exporting the content of the list into Excel. Then from there you can edit the content and then update the records in grid view. If you use Grid View, just make sure your Excel is in the same order as the view so you don't accidentally poste one assets data over another.

Sorry this isn't better news but we don't have any control over how or when Microsoft changes SharePoint or Teams.

**Comment by luvsql** [comment] 2024-11-07 13:56
Can we not control the viewer setting?  From what Copilot is saying there is someone to change the CSP (Content Security Policy) as the error shows "frame-ancestors 'none'"  Can we not change the viewer setting?  This viewer setting change would affect thousands and possibly millions of customers.  The fix cant' be to change all of the links.

**Comment by dcashpeterson** [comment] 2024-11-08 14:13
@luvsql I understand the frustration. This has nothing to do with the Learning Pathways viewer webpart. It's the viewer that M365 is using to show documents. I do not know of any way in the user interface to make that change in M365.

**Comment by luvsql** [comment] 2024-11-08 14:15
Why is it only this site that is affected if it's a globak viewer change?

**Comment by dcashpeterson** [comment] 2024-11-08 14:20
@luvsql This isn't specific to Learning Pathways. The URLs that are put in for the assets are brought into the Learning Pathways viewer webpart using an IFrame. If you tried to put that same URL into an Iframe using the Embed webpart on any SharePoint page it would not work. The issue is that the viewer (the page you are linking to) has that value in it's header. We have no control over the header of that viewer. It's bulit into the M365 product.

**Comment by dcashpeterson** [comment] 2024-11-26 12:40
Closing as answered.

**Closed by dcashpeterson** 2024-11-26 12:40 UTC
Labels: status: details needed, type: something isn't working
