### ISSUE TITLE
CLO unable to open in IE 11

### ISSUE THREAD

**Issue by jonathanturk** [pnp/custom-learning-office-365#19] opened 2019-03-28 18:40 UTC
![CLOIE](https://user-images.githubusercontent.com/49040826/55183873-32f66280-5167-11e9-8d46-342e8ece6662.png)

CLO is unable to be opened in IE 11, image details what happens with the error "The CustomLearningWebPart has not been properly configured and you do not have Owner rights to complete the operation. Please contact the site administrator."

**Comment by juliemturner** [comment] 2019-04-05 17:33
Duplicate of #18

**Closed by juliemturner** 2019-04-05 17:33 UTC
Labels: bug
