### ISSUE TITLE
Bug - iframe height is larger than content 

### ISSUE THREAD

**Issue by andikrueger** [pnp/custom-learning-office-365#337] opened 2020-08-12 12:16 UTC
## Describe the bug

When using the webpart to display a playlist item, the webpart uses a height of 6000px. The height of the container is larger than the content.

![learningpathwaysbug](https://user-images.githubusercontent.com/15608729/90013704-15676180-dca6-11ea-94bd-c5ffb22b53b9.png)

### Expected behavior

The webpart is large enough to show the iframe without scroll bars.

### Screenshots

see above.

### Learning Pathways version number

4.1.2.0

**Comment by juliemturner** [comment] 2020-08-12 13:02
Duplicate of #171

**Closed by juliemturner** 2020-08-12 13:02 UTC
Labels: area: content, status: duplicate, type: bug

**Comment by andikrueger** [comment] 2020-08-12 13:11
Any chance you could get the height from the iFrame itself?

**Comment by juliemturner** [comment] 2020-08-12 13:20
You cannot no, the height of the iFrame is based on the content inside of the iFrame, the only way to get the height of the content inside the iFrame in a CORS situation is to implement postMessage solution, which support.office.com did but unfortunately they have a bug. They're sending 6000 back regardless of the content height, upon first call.  Subsequent calls work correctly, so if you move to the next asset and then move back it's fine.  docs.microsoft.com has yet to implement the postMessage solution and so anytime that content is included it is automatically defaulted to 6000. Custom content is not a CORS situation so I can read the height of the internal content directly.
