### ISSUE TITLE
 Edge/Chrome with version 85+ fail to load video content

### ISSUE THREAD

**Issue by matthewjob** [pnp/custom-learning-office-365#341] opened 2020-08-18 08:06 UTC
## Describe the bug

All Chromium based browsers (Edge and Chrome) past version 85 cannot load video content.
All Chromium based browser with version 84 and below cannot load video content if additional referrer security is enabled.

### To Reproduce

1. Open the Learning Pathways Site in Edge or Chrome
2. Select any content that contains a video (eg What is Microsoft Teams)
3. All content loads except the video

### Expected behavior

Video loads and plays without issue

### Screenshots

![LearningPathwaysError](https://user-images.githubusercontent.com/31902455/90484546-aee8b480-e179-11ea-994b-9987d6c73ecd.png)

### Learning Pathways version number

3.x
4.1.x

### Additional context

**Workaround for Edge/Chrome 85/86**
1. Load edge://flags  (chrome://flags for Chrome)
2. Search for referrer
3. Disable **Reduce default 'referrer' header granularity**
4. Restart browser.

![Edge_Referrer_Flag](https://user-images.githubusercontent.com/31902455/90485052-5b2a9b00-e17a-11ea-9d43-0f469b362e9d.png)

For Edge/Chrome 84 and below, perform the same steps except Enable this setting to replicate Edge/Chrome 85+ default behavior.

### Detailed diagnosis

From Fiddler traces with Edge 85+
1.	Once the page loads, the page attempts to get the video player from https://videoplayercdn.osi.office.net/s/js/vxp.js with referrer as https://support.office.com
2.	This page returns a 302 and redirects the browser to https://www.microsoft.com/videoplayer/js/vxpiframe.js
3.	The browser attempts to load https://www.microsoft.com/client/en-us/videoplayer/embed/RE1LGec?pid=ocpVideo0-innerdiv-oneplayer&jsapi=true&postJsllMsg=true&maskLevel=20&market=en-us
4.	Another 302 to https://www.microsoft.com/en-au/client/en-us/videoplayer/embed/RE1LGec?pid=ocpVideo0-innerdiv-oneplayer&jsapi=true&postJsllMsg=true&maskLevel=20&rtc=1
5.	Resulting in another 302 redirect to Location: https://www.microsoft.com/library/errorpages/smarterror.aspx?correlationId=pLDNP7MeMEekH1X8.0.3.0
6.	And finally a 404 as this page is not available.

When Reduce default 'referrer' header granularity is disabled or default behavior in Edge/Chrome 84 and below.
1.	Request to https://videoplayercdn.osi.office.net/s/js/vxp.js as before but this time with the referrer as https://support.office.com/en-us/client/4422bf3aa-9ae8-46f1-83a2-e65720e1a34d?embed=true&fromOrigin=https://tenantnameremoved.sharepoint.com
2.	This redirects to https://support.office.com/client/videoplayer/js/vxpiframe.js now which allows the video to load.

**Root Cause:** Video player requires the additional query strings to determine the correct site to redirect the browser and find the video player.

**Comment by juliemturner** [comment] 2020-08-18 13:48
Duplicate #333

**Comment by matthewjob** [comment] 2020-09-01 19:58
Heard back from Microsoft.  A fix for this issue has been deployed worldwide.  Testing in our environments shows that this is resolved.

**Comment by juliemturner** [comment] 2020-09-01 20:46
I can confirm that I have also been told the issue is fixed.  Closing, thanks all for reporting.

**Closed by juliemturner** 2020-09-01 20:46 UTC
Labels: area: content, status: duplicate, status: needs review, type: something isn't working
