### ISSUE TITLE
Video content is not visible on iOS devices 

### ISSUE THREAD

**Issue by stuartridout** [pnp/custom-learning-office-365#496] opened 2021-04-13 13:43 UTC
## Describe the bug

When browsing Learning Pathways content on iOS the video loading screen is briefly shown for a fraction of a second and then disappears leaving a white gap.  No video content is loaded.  Applies to Safari, Edge and Chrome on iOS.

If you browse to similar content on support.microsoft.com the video content loads correctly.

### To Reproduce

Open a Learning Pathways site in Safari, Edge or Chrome.
Browse to the Microsoft 365 training
Pick some content that has a video

### Expected behavior

Video loads in the same way as a Windows device would.

### Screenshots

![20210413_132611000_iOS](https://user-images.githubusercontent.com/6738750/114561511-8744e000-9c65-11eb-8748-7ba72f87580d.png)
![20210413_132627000_iOS](https://user-images.githubusercontent.com/6738750/114561515-87dd7680-9c65-11eb-82c0-21d0fc8b0d8e.png)

### Learning Pathways version number

Learning Pathways 4.1.4
iOS 14.4.2
Also tried iOS 12.4.8 and that didn't work either

**Comment by jnewgard-thrive** [comment] 2021-04-13 16:18
Hi @stuartridout,

What type of network is the device connected to when the issue reproduces? (Office, Home, Mobile, etc)

- Does it work as expected on any of these network types?
- If you access the Learning Pathways site via desktop/laptop on the same network, does the issue still occur?

Is the device under any type of management software (MDM) such as Intune or similar?

---

This behavior is suggestive of a security configuration preventing the content be loaded from support.office.com as embedded content.

**Comment by stuartridout** [comment] 2021-04-13 16:22
@jnewgard-thrive this is from a variety of locations.  It doesn't seem to make a difference.  My tests were done on a personal laptop with no corporate restrictions on a vanilla build.  

The behaviour is not the same as on a desktop/laptop device.  This appears to be restricted to iOS.

**Comment by juliemturner** [comment] 2021-04-13 22:21
So, I tested this on my iPhone and can replicate the error however, I think the missing link is (maybe) the URL you used to test this as a stand-alone page. 

`https://support.office.com/en-us/client/4422bf3aa-9ae8-46f1-83a2-e65720e1a34d?embed=true&fromOrigin=https://sympjulie.sharepoint.com`

When I did so with the following URL which is what is loaded in the iFrame the video doesn't load.  At this point there is nothing more I can do from a development standpoint as this is then an issue with support.office.com. I'll tag this as a content bug and pass on to the appropriate team.  Thanks for reporting it.

![iosissue](https://user-images.githubusercontent.com/7570936/114628564-0990cc80-9c85-11eb-863e-84c0315d8f7a.jpg)

**Comment by stuartridout** [comment] 2021-04-15 21:29
Hi Julie.  The link that I got working from support.microsoft.com was https://support.microsoft.com/en-gb/office/video-what-is-microsoft-teams-422bf3aa-9ae8-46f1-83a2-e65720e1a34d

**Comment by juliemturner** [comment] 2021-04-16 21:01
Yes, but that is not the link I posted above which is the link that is required to render content for learning pathways, it removes certain aspects of the chrome on the page. 
>https://support.office.com/en-us/client/4422bf3aa-9ae8-46f1-83a2-e65720e1a34d?embed=true&fromOrigin=https://sympjulie.sharepoint.com

So, as I said the issue is with the support.office.com platform and not learning pathways particularly and so there is nothing more I can do from a development perspective. I have communicated with the content team that they appear to have a problem.

**Comment by schumaho** [comment] 2021-09-03 10:32
Any updates or news on this problem? We have the same issue that the videos are not shown at all, but only a blank screen instead of the video.
Thanks for any further suggestions or help!

Best regards,
Max

**Comment by sbstn3schfr** [comment] 2021-12-10 07:29
@peterjkrebs any updates about the iOS video integration?

**Comment by dcashpeterson** [comment] 2024-05-14 09:05
Closed as fixed.

**Closed by dcashpeterson** 2024-05-14 09:05 UTC
Labels: type: bug, area: content, status: needs review
