### ISSUE TITLE
Learning pathways Feature Updates Q2 - Languages not availabe - its not Q3 

### ISSUE THREAD

**Issue by MCL2020** [pnp/custom-learning-office-365#287] opened 2020-07-02 08:40 UTC
Hi the announced language updates are not available

https://docs.microsoft.com/en-us/office365/customlearning/custom_featureupdates

**What is the roadmap? When will they become available?**

Upcoming Feature Updates for Q2 2020
Multilingual support for learning pathways is scheduled to release in the second quarter of 2020. Multilingual support takes a dependency on the “Multiligual page publishing for Modern SharePoint” feature and will be available at the same time as General Availability for SharePoint multilingual support. For more information, see the Microsoft 365 Roadmap.

The following languages will be supported for learning pathways:

Chinese (Simplified)
French
German
Italian (Italy)
Japanese (Japan)
Portuguese (Brazilian)
Russian (Russian)
Spanish

**Comment by juliemturner** [comment] 2020-07-02 13:23
Duplicate of #280

**Closed by juliemturner** 2020-07-02 13:23 UTC
Labels: type: something isn't working
